apiVersion: v1
kind: Service
metadata:
  name: service-canary
spec:
  selector:
    app: rollouts-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: service-stable
spec:
  selector:
    app: rollouts-example
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
