apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rollouts-ingress
spec:
  rules:
    - host: rollouts.ginger-ous.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: service-stable
                port:
                  number: 8080
